BEGIN TRANSACTION;

DROP TABLE IF EXISTS test1_a;
DROP TABLE IF EXISTS test1_b;

CREATE TABLE test1_a (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    b integer
);

CREATE TABLE test1_b (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

DROP TABLE IF EXISTS test2_a;
DROP TABLE IF EXISTS test2_b;
DROP TABLE IF EXISTS test2_c;

CREATE TABLE test2_a (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    b integer
);

CREATE TABLE test2_b (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    c integer
);

CREATE TABLE test2_c (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

COMMIT;
