BEGIN TRANSACTION;

DROP TABLE IF EXISTS main;
DROP TABLE IF EXISTS belongs;
DROP TABLE IF EXISTS many;
DROP TABLE IF EXISTS might;
DROP TABLE IF EXISTS other;

CREATE TABLE main (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    might INTEGER,
    belongs INTEGER NOT NULL
);

CREATE TABLE belongs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    other INTEGER NOT NULL
);

CREATE TABLE many (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    main INTEGER NOT NULL
);

CREATE TABLE might (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

CREATE TABLE other (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

COMMIT;
